site_name: CLIFpy Documentation
site_description: Python Client for Common Longitudinal ICU data Format
site_author: CLIF Consortium
site_url: https://common-longitudinal-icu-data-format.github.io/clifpy/
repo_url: https://github.com/Common-Longitudinal-ICU-data-Format/clifpy
repo_name: clifpy

theme:
  name: material
  logo: images/clif_logo_no_text_white.png  
  favicon: images/clif_logo_red_no_text.png  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: slate
      primary: maroon
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_root_toc_entry: true
            docstring_style: numpy
            merge_init_into_class: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - def_list
  - sane_lists

nav:
  - Home: index.md
  - User Guide:
      - Overview: user-guide/index.md
      - Getting Started:
        - Installation: user-guide/installation.md
        - Quickstart: user-guide/quickstart.md
      - Core Features:
        - Data Validation: user-guide/validation.md
        - Outlier Handling: user-guide/outlier-handling.md
        - Encounter Stitching: user-guide/encounter-stitching.md
        - Wide Dataset Creation: user-guide/wide-dataset.md
        - Working with Timezones: user-guide/timezones.md
      - Advanced Features:
        - Medication Unit Conversion: user-guide/med-unit-conversion.md
        - SOFA Score Computation: user-guide/sofa.md
        - Respiratory Support Waterfall: user-guide/waterfall.md
        - Comorbidity Index: user-guide/comorbidity-index.md
  - API Reference:
      - Overview: api/index.md
      - Orchestrator: api/orchestrator.md
      - Base Table: api/base-table.md
      - Tables: api/tables.md
      - Utilities: api/utilities.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Common-Longitudinal-ICU-data-Format/CLIFpy
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/dark-mode-default.js