[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyclif"
version = "2.0.0"
description = "A Python package for working with CLIF EHR data"
readme = "README.md"
license = { text = "Apache Software License" }
authors = [
  { name = "Kaveri Chhikara", email = "kaveri.chhikara@gmail.com" }
]
classifiers = [
  "Programming Language :: Python :: 3.9",
  "Operating System :: OS Independent"
]
requires-python = ">=3.9"
dependencies = [
  "pandas>=1.0",
  "duckdb>=0.5.0",
  "pyarrow",
  "matplotlib",
  "seaborn"
]

[tool.setuptools]
license-files = []

[tool.setuptools.packages.find]
include = ["schemas", "utils", "tests"]
