[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyclif"  
version = "2.0.0"
description = "A Python package for working with CLIF EHR data"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Kaveri Chhikara", email = "kaveri.chhikara@gmail.com"}
]
classifiers = [
  "Programming Language :: Python :: 3.9",
  "License :: OSI Approved :: Apache 2.0",
  "Operating System :: OS Independent"
]
requires-python = ">=3.9"
dependencies = [
  "pandas>=1.0",
  "duckdb>=0.5.0",
  "pyarrow",
  "matplotlib",
  "seaborn",
  "datetime", 
  "re"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pyclif"]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
