"""Shared config, logging, drug list and privacy guards.

Every number this analysis writes is an aggregate. Nothing patient-level is ever
persisted, so there is a single output directory and no PHI tier to keep
separate -- see `assert_no_identifiers` and `suppress_small_cells`, which are
enforced at write time rather than left to discipline.
"""

from __future__ import annotations

import json
import logging
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

logger = logging.getLogger('weighted_unit_impact')

REPO_ROOT = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# The drugs under study
# ---------------------------------------------------------------------------
# Every med_category whose CLIF 3.0 mCIDE target carries /kg but which at least
# one consortium site charts on an unweighted unit -- i.e. exactly the set where
# standardizing to the mCIDE target forces an unweighted -> weighted conversion.
#
# Generated by .dev/_scratch/forced_drug_list.py from the 11-site DQA inventory.
# Ordered by consortium-wide forced volume. A site narrows this with
# `drug_subset` in its config rather than editing here.
FORCED_CONVERSION_DRUGS: dict[str, str] = {
    'norepinephrine':  'mcg/kg/min',   # vasoactive,        8,625,042 obs forced
    'heparin':         'units/kg/hr',  # anticoagulant,     3,768,107
    'phenylephrine':   'mcg/kg/min',   # vasoactive,        2,320,723
    'epinephrine':     'mcg/kg/min',   # vasoactive,        1,409,080
    'propofol':        'mcg/kg/min',   # sedative,            322,686
    'ketamine':        'mg/kg/hr',     # sedative,            206,812
    'tacrolimus':      'mcg/kg/day',   # immunosuppressant,   129,313
    'dexmedetomidine': 'mcg/kg/hr',    # sedative,             63,552
    'isoproterenol':   'mcg/kg/min',   # vasoactive,           54,314
    'epoprostenol':    'ng/kg/min',    # pulm vasodilator,     32,078
    'naloxone':        'mcg/kg/hr',    # reversal,             21,758
    'cisatracurium':   'mcg/kg/min',   # paralytic,            17,084
    'rocuronium':      'mcg/kg/min',   # paralytic,             8,137
    'dopamine':        'mcg/kg/min',   # vasoactive,            4,785
    'milrinone':       'mcg/kg/min',   # vasoactive,            3,662
    'dobutamine':      'mcg/kg/min',   # vasoactive,            1,860
    'esmolol':         'mcg/kg/min',   # vasoactive,            1,486
    'vecuronium':      'mcg/kg/min',   # paralytic,             1,055
    'nitroprusside':   'mcg/kg/min',   # vasoactive,              899
    'eptifibatide':    'mcg/kg/min',   # antiplatelet,            750
    'treprostinil':    'ng/kg/min',    # pulm vasodilator,        545
    'bivalirudin':     'mcg/kg/hr',    # anticoagulant,           528
    'cangrelor':       'mcg/kg/min',   # antiplatelet,            365
    'argatroban':      'mcg/kg/min',   # anticoagulant,           296
    'remifentanil':    'mcg/kg/min',   # analgesic,               111
    'zidovudine':      'mg/kg/hr',     # antiviral,                97
    'pentobarbital':   'mg/kg/hr',     # sedative,                 72
    'aminophylline':   'mg/kg/hr',     # bronchodilator,           54
    'angiotensin':     'ng/kg/min',    # vasoactive,               13
}

# Clinical family, for readability in the report only.
DRUG_FAMILY: dict[str, str] = {
    'norepinephrine': 'vasoactive', 'epinephrine': 'vasoactive',
    'phenylephrine': 'vasoactive', 'dopamine': 'vasoactive',
    'dobutamine': 'vasoactive', 'milrinone': 'vasoactive',
    'angiotensin': 'vasoactive', 'isoproterenol': 'vasoactive',
    'esmolol': 'vasoactive', 'nitroprusside': 'vasoactive',
    'epoprostenol': 'pulm vasodilator', 'treprostinil': 'pulm vasodilator',
    'propofol': 'sedative', 'ketamine': 'sedative',
    'dexmedetomidine': 'sedative', 'pentobarbital': 'sedative',
    'remifentanil': 'analgesic', 'naloxone': 'reversal',
    'cisatracurium': 'paralytic', 'rocuronium': 'paralytic',
    'vecuronium': 'paralytic',
    'heparin': 'anticoagulant', 'bivalirudin': 'anticoagulant',
    'argatroban': 'anticoagulant', 'eptifibatide': 'antiplatelet',
    'cangrelor': 'antiplatelet', 'tacrolimus': 'immunosuppressant',
    'zidovudine': 'antiviral', 'aminophylline': 'bronchodilator',
}

# Column names that must never appear in an output file. Matched exactly and as
# a suffix, so `hospitalization_id` and `enc_id` are both caught.
_ID_EXACT = {
    'hospitalization_id', 'patient_id', 'encounter_block', 'encounter_id',
    'hospitalization_joined_id', 'med_order_id', 'mrn', 'subject_id',
    'stay_id', 'hadm_id', 'icustay_id',
}
_ID_SUFFIX = re.compile(r'(^|_)id$', re.IGNORECASE)


@dataclass
class Settings:
    """Resolved site configuration."""

    site_name: str
    config_path: Path
    clif_version: str
    data_directory: str
    filetype: str
    timezone: str
    weight_staleness_days: int = 7
    min_cell_size: int = 11
    drug_subset: list[str] | None = None
    output_dir: Path = field(init=False)

    def __post_init__(self) -> None:
        self.output_dir = (
            REPO_ROOT / 'output' / 'weighted_unit_impact' / self.site_name
        )

    @property
    def drugs(self) -> dict[str, str]:
        """Drugs to analyse, mCIDE target unit each."""
        if not self.drug_subset:
            return dict(FORCED_CONVERSION_DRUGS)
        unknown = set(self.drug_subset) - set(FORCED_CONVERSION_DRUGS)
        if unknown:
            raise ValueError(
                f"drug_subset names drugs that are not forced-conversion "
                f"candidates: {sorted(unknown)}. "
                f"Valid: {sorted(FORCED_CONVERSION_DRUGS)}"
            )
        return {d: FORCED_CONVERSION_DRUGS[d] for d in self.drug_subset}


def load_settings(config_path: str | Path) -> Settings:
    """Read and validate a site config.

    `clif_version` is required rather than defaulted. clifpy falls back to
    "3.0", and a 2.1 dataset loaded as 3.0 validates against the wrong schema
    silently -- so refusing to start is much safer than guessing.
    """
    path = Path(config_path).expanduser()
    if not path.is_file():
        raise FileNotFoundError(f"config not found: {path}")
    cfg: dict[str, Any] = yaml.safe_load(path.read_text()) or {}

    required = ['site_name', 'data_directory', 'filetype', 'timezone', 'clif_version']
    missing = [k for k in required if not cfg.get(k)]
    if missing:
        raise ValueError(
            f"{path} is missing required field(s): {missing}. "
            f"Copy config_template.yaml and fill in every field -- "
            f"`clif_version` in particular has no safe default."
        )

    if not Path(cfg['data_directory']).is_dir():
        raise FileNotFoundError(
            f"data_directory does not exist: {cfg['data_directory']}"
        )

    return Settings(
        site_name=str(cfg['site_name']),
        config_path=path,
        clif_version=str(cfg['clif_version']),
        data_directory=str(cfg['data_directory']),
        filetype=str(cfg['filetype']),
        timezone=str(cfg['timezone']),
        weight_staleness_days=int(cfg.get('weight_staleness_days', 7)),
        min_cell_size=int(cfg.get('min_cell_size', 11)),
        drug_subset=cfg.get('drug_subset') or None,
    )


def setup_logging(settings: Settings) -> logging.Logger:
    """Log to stdout and to a file inside the site's output directory."""
    settings.output_dir.mkdir(parents=True, exist_ok=True)
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    fmt = logging.Formatter('%(asctime)s  %(levelname)-7s %(message)s', '%H:%M:%S')

    stream = logging.StreamHandler()
    stream.setFormatter(fmt)
    logger.addHandler(stream)

    fileh = logging.FileHandler(settings.output_dir / 'run.log', mode='w')
    fileh.setFormatter(fmt)
    logger.addHandler(fileh)

    logger.propagate = False
    return logger


# ---------------------------------------------------------------------------
# Privacy guards -- enforced, not advisory
# ---------------------------------------------------------------------------

def assert_no_identifiers(df: pd.DataFrame, where: str) -> None:
    """Refuse to write a frame carrying anything ID-shaped.

    Called by `write_output` on every file, so a column added later cannot
    quietly become part of a shared artefact.
    """
    offenders = [
        c for c in df.columns
        if c.lower() in _ID_EXACT or _ID_SUFFIX.search(c)
    ]
    if offenders:
        raise ValueError(
            f"refusing to write {where}: identifier-shaped column(s) "
            f"{offenders}. Aggregate before writing; IDs stay in memory."
        )


def suppress_small_cells(
    df: pd.DataFrame,
    count_col: str,
    min_cell: int,
    keep_cols: list[str] | None = None,
) -> pd.DataFrame:
    """Blank out rows describing fewer than `min_cell` subjects.

    The row is kept with the count nulled and `suppressed=True`, rather than
    dropped. A dropped row is indistinguishable from a true zero when pooling,
    which would bias the consortium picture toward sites that happen to be
    small.
    """
    out = df.copy()
    mask = out[count_col].fillna(0) < min_cell
    out['suppressed'] = mask
    numeric = [
        c for c in out.select_dtypes('number').columns
        if c not in (keep_cols or [])
    ]
    out.loc[mask, numeric] = pd.NA
    return out


def write_output(df: pd.DataFrame, settings: Settings, name: str) -> Path:
    """Write one aggregate CSV, after the identifier check."""
    assert_no_identifiers(df, name)
    settings.output_dir.mkdir(parents=True, exist_ok=True)
    dest = settings.output_dir / name
    df.to_csv(dest, index=False)
    logger.info('wrote %s (%d rows)', dest.relative_to(REPO_ROOT), len(df))
    return dest


def git_commit() -> str:
    """Short commit of the analysis code, for the manifest."""
    try:
        return subprocess.run(
            ['git', 'rev-parse', '--short', 'HEAD'],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=5,
        ).stdout.strip() or 'unknown'
    except Exception:
        return 'unknown'


def write_manifest(settings: Settings, manifest: dict[str, Any]) -> Path:
    """Record what ran, what was skipped, and why.

    A partial return is then interpretable centrally without a follow-up email,
    which matters because most sites running this cannot be debugged
    interactively.
    """
    import clifpy

    payload = {
        'site_name': settings.site_name,
        'clif_version': settings.clif_version,
        'clifpy_version': getattr(clifpy, '__version__', 'unknown'),
        'analysis_commit': git_commit(),
        'min_cell_size': settings.min_cell_size,
        'weight_staleness_days': settings.weight_staleness_days,
        'drugs_requested': sorted(settings.drugs),
        **manifest,
    }
    dest = settings.output_dir / 'run_manifest.json'
    dest.write_text(json.dumps(payload, indent=2, default=str))
    logger.info('wrote %s', dest.relative_to(REPO_ROOT))
    return dest
